service: basic-lambda

provider:
  name: aws
  runtime: python3.11
  region: us-east-1            # choose the region you want for HB
  stage: dev
  profile: hb-client              # the profile that assumes the client's role
  logRetentionInDays: 14

functions:
  hello:
    handler: handler.hello
    memorySize: 128
    timeout: 10
    description: "Test lambda deployed via Serverless Framework"